"""
Base Strategy Interface
========================
Abstract base class for all trading strategies.
Defines the common interface and signal format.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any

import pandas as pd


class SignalType(Enum):
    BUY_CALL = "BUY_CALL"
    BUY_PUT = "BUY_PUT"
    HOLD = "HOLD"
    NO_SIGNAL = "NO_SIGNAL"


@dataclass
class StrategySignal:
    """A trading signal generated by a strategy."""
    strategy_name: str
    signal_type: SignalType
    symbol: str
    confidence: float  # 0-100
    entry_price: float = 0.0
    target1: float = 0.0
    target2: float = 0.0
    stop_loss: float = 0.0
    reason: str = ""
    indicators: Dict[str, float] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)
    
    @property
    def is_actionable(self) -> bool:
        return self.signal_type in (SignalType.BUY_CALL, SignalType.BUY_PUT)


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""
    
    def __init__(self, name: str):
        self.name = name
        self._signals_history: List[StrategySignal] = []
    
    @abstractmethod
    def generate_signal(self, df: pd.DataFrame, symbol: str) -> StrategySignal:
        """Generate a trading signal from the given data."""
        pass
    
    @abstractmethod
    def get_parameters(self) -> Dict[str, Any]:
        """Return current strategy parameters."""
        pass
    
    @abstractmethod
    def set_parameters(self, params: Dict[str, Any]):
        """Update strategy parameters."""
        pass
    
    def add_to_history(self, signal: StrategySignal):
        """Record a signal in history."""
        self._signals_history.append(signal)
        if len(self._signals_history) > 500:
            self._signals_history = self._signals_history[-500:]
    
    def get_history(self) -> List[StrategySignal]:
        return self._signals_history.copy()
    
    def get_win_rate(self) -> float:
        """Calculate historical win rate (placeholder - needs trade results)."""
        actionable = [s for s in self._signals_history if s.is_actionable]
        if not actionable:
            return 0.0
        # Placeholder: would need actual trade outcomes
        return 0.0
